//! WASM rule engine for fywaf backed by OWASP CRS rules.
//!
//! This crate compiles to `wasm32-unknown-unknown` and exports the four
//! functions required by fywaf's WASM module interface:
//!
//! - `get_req_ptr() -> i32`  — pointer to the request JSON input buffer
//! - `decide(req_len: i32) -> i32` — evaluate rules; returns result length
//! - `get_result_ptr() -> i32` — pointer to the decision JSON output buffer
//!
//! The rule set is embedded at compile time from `OUT_DIR/crs_rules.json`
//! (generated by `build.rs`).

// `no_std` only on the actual WASM target.  When running host tests (cargo
// test) we compile for the host architecture which requires std, and using
// `std::sync` primitives for thread-safe access to the regex cache.
#![cfg_attr(target_arch = "wasm32", no_std)]

// On wasm32 all collection/string types come from `alloc`; on the host they
// come from `std::prelude` automatically.
#[cfg(target_arch = "wasm32")]
extern crate alloc;
#[cfg(target_arch = "wasm32")]
use alloc::{collections::BTreeMap, format, string::String, vec::Vec};
#[cfg(not(target_arch = "wasm32"))]
use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};

mod engine;
mod operators;
mod transforms;

use engine::evaluate;

// ---------------------------------------------------------------------------
// Embedded rule data — parsed once and cached
// ---------------------------------------------------------------------------

static CRS_RULES_JSON: &str = include_str!(concat!(env!("OUT_DIR"), "/crs_rules.json"));

/// Result of parsing the embedded rule JSON.
enum RulesState {
    /// Successfully parsed rules.
    Ok(Vec<crs_parser::Rule>),
    /// JSON was malformed — fail-closed on every request.
    ParseError,
}

struct RulesCache(core::cell::UnsafeCell<Option<RulesState>>);
// SAFETY: The WASM target is single-threaded; there is no concurrent access.
unsafe impl Sync for RulesCache {}
static RULES_CACHE: RulesCache = RulesCache(core::cell::UnsafeCell::new(None));

/// Return the cached rules, or `Err(())` if the embedded JSON failed to parse.
///
/// Callers must treat `Err` as a fail-closed condition (block the request).
fn get_rules() -> Result<&'static [crs_parser::Rule], ()> {
    // SAFETY: WASM is single-threaded; `decide` is never re-entered.
    unsafe {
        let slot = &mut *RULES_CACHE.0.get();
        if slot.is_none() {
            *slot = Some(
                match serde_json::from_str::<Vec<crs_parser::Rule>>(CRS_RULES_JSON) {
                    Ok(rules) => RulesState::Ok(rules),
                    Err(_) => RulesState::ParseError,
                },
            );
        }
        match slot.as_ref().unwrap() {
            RulesState::Ok(rules) => Ok(rules.as_slice()),
            RulesState::ParseError => Err(()),
        }
    }
}

// ---------------------------------------------------------------------------
// WASM shared memory buffers
// ---------------------------------------------------------------------------

const BUF_LEN: usize = 65536;

static mut REQ_BUF: [u8; BUF_LEN] = [0u8; BUF_LEN];
static mut RESULT_BUF: [u8; BUF_LEN] = [0u8; BUF_LEN];

// ---------------------------------------------------------------------------
// JSON protocol types (mirrors fywaf's WasmRequest / WasmDecision)
// ---------------------------------------------------------------------------

#[derive(Deserialize)]
struct Request<'a> {
    #[serde(default)]
    method: &'a str,
    #[serde(default)]
    path: &'a str,
    query: Option<&'a str>,
    user_agent: Option<&'a str>,
    #[serde(default)]
    headers: BTreeMap<&'a str, &'a str>,
    body: Option<&'a str>,
    /// Optional profile parameters passed from fywaf config.
    #[serde(default)]
    params: BTreeMap<&'a str, serde_json::Value>,
}

#[derive(Serialize)]
struct Decision {
    allow: bool,
    status: u16,
    #[serde(skip_serializing_if = "Option::is_none")]
    message: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    rule_id: Option<String>,
}

// ---------------------------------------------------------------------------
// WASM exports
// ---------------------------------------------------------------------------

#[unsafe(no_mangle)]
pub extern "C" fn get_req_ptr() -> i32 {
    core::ptr::addr_of!(REQ_BUF) as i32
}

#[unsafe(no_mangle)]
pub extern "C" fn get_result_ptr() -> i32 {
    core::ptr::addr_of!(RESULT_BUF) as i32
}

/// Evaluate the CRS rules against the request in `REQ_BUF[..req_len]`.
///
/// Writes the decision JSON into `RESULT_BUF` and returns the byte length.
#[unsafe(no_mangle)]
pub extern "C" fn decide(req_len: i32) -> i32 {
    let req_len = (req_len as usize).min(BUF_LEN);
    let req_bytes =
        unsafe { core::slice::from_raw_parts(core::ptr::addr_of!(REQ_BUF) as *const u8, req_len) };

    let decision = match core::str::from_utf8(req_bytes) {
        Err(_) => bad_request(),
        Ok(json_str) => match serde_json::from_str::<Request<'_>>(json_str) {
            Err(_) => bad_request(),
            Ok(req) => run_rules(&req),
        },
    };

    write_result(&decision)
}

// ---------------------------------------------------------------------------
// Rule evaluation
// ---------------------------------------------------------------------------

fn run_rules(req: &Request<'_>) -> Decision {
    // Read paranoia_level from params (default 1).
    let paranoia_level: u8 = req
        .params
        .get("paranoia_level")
        .and_then(|v| v.as_u64())
        .map(|n| n.min(4) as u8)
        .unwrap_or(1);

    // Anomaly threshold (default 5 = one CRITICAL hit).
    let anomaly_threshold: u32 = req
        .params
        .get("anomaly_threshold")
        .and_then(|v| v.as_u64())
        .map(|n| n as u32)
        .unwrap_or(5);

    // Use the cached (pre-parsed) rule set — no per-request deserialization.
    let rules = match get_rules() {
        Ok(r) => r,
        // Fail closed: if the embedded rule JSON is malformed we must not
        // allow requests through uninspected — return 500 Internal Error.
        Err(()) => {
            return Decision {
                allow: false,
                status: 500,
                message: Some(String::from("internal error: rule set unavailable")),
                rule_id: None,
            }
        }
    };

    evaluate(
        rules,
        req.method,
        req.path,
        req.query,
        req.user_agent,
        &req.headers,
        req.body,
        paranoia_level,
        anomaly_threshold,
    )
    .map(|(rule_id, msg)| Decision {
        allow: false,
        status: 403,
        message: Some(msg),
        rule_id: Some(format!("{}", rule_id)),
    })
    .unwrap_or_else(allow)
}

fn allow() -> Decision {
    Decision {
        allow: true,
        status: 200,
        message: None,
        rule_id: None,
    }
}

/// Return a fail-closed decision for malformed (non-UTF-8 / non-JSON) requests.
///
/// A WAF must never allow a request that it cannot inspect; returning 400
/// prevents trivial bypass via malformed payloads.
fn bad_request() -> Decision {
    Decision {
        allow: false,
        status: 400,
        message: Some(String::from("bad request")),
        rule_id: None,
    }
}

fn write_result(decision: &Decision) -> i32 {
    let json = serde_json::to_string(decision).unwrap_or_default();
    let bytes = json.as_bytes();
    let copy_len = bytes.len().min(BUF_LEN);
    unsafe {
        let dst = core::ptr::addr_of_mut!(RESULT_BUF) as *mut u8;
        core::ptr::copy_nonoverlapping(bytes.as_ptr(), dst, copy_len);
    }
    copy_len as i32
}
